CREATE TABLE IF NOT EXISTS catalogues (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    brand_id INT,
    category_id INT,
    screen_size VARCHAR(255),
    front_camera VARCHAR(255),
    rear_camera VARCHAR(255),
    ram VARCHAR(255),
    storage VARCHAR(255),
    battery VARCHAR(255),
    os VARCHAR(255),
    specifications TEXT,
    price DECIMAL(10, 2) NOT NULL,
    published_at TIMESTAMP NULL DEFAULT NULL,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_by VARCHAR(255) NULL,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (brand_id) REFERENCES brands(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);
